allowLineBreaksInTitles: false
color: pink
description: null
fieldLayouts:
  fa8beb1c-e5bc-4b50-bb01-40b536be927a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T20:38:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b688f2ad-48f2-460c-ad2c-ad3dc97599ca # Device Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72018c63-4ade-4ae9-a419-0a736197da2b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T20:38:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb89e543-0de1-4a53-9480-2e7c0e8a69a5 # Aspect Ratio
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63164398-a80d-4596-8047-a50454edeee5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T20:38:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b81cc92d-9e5b-440d-8461-cdf9ab64807e # Opacity
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d589cff-51d5-44e0-9400-c4c9ee3a5cc0
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 2c66658d-872c-41ec-908b-0bb243c2f46f
        userCondition: null
    thumbFieldKey: null
handle: pageHeaderArtDirection
hasTitleField: false
icon: null
name: 'Page Header Art Direction'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{object.owner.title}-{deviceSize}-PageHeaderArtDirection'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
