columnSuffix: null
handle: cardContent
instructions: null
name: 'Card Content'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels: false
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: null
  jsFile: null
  options:
    __assoc__:
      -
        - fontSize
        -
          __assoc__:
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - model
                      - xs
                    -
                      - title
                      - 'Extra Small'
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-xs
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - sm
                    -
                      - title
                      - Small
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-sm
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - lg
                    -
                      - title
                      - Large
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-lg
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - xl
                    -
                      - title
                      - 'Extra Large'
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 2xl
                    -
                      - title
                      - 2XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-2xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 3xl
                    -
                      - title
                      - 3XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-3xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 4xl
                    -
                      - title
                      - 4XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-4xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 5xl
                    -
                      - title
                      - 5XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-5xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 6xl
                    -
                      - title
                      - 6XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-6xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 7xl
                    -
                      - title
                      - 7XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-7xl
                          -
                            - name
                            - span
                -
                  __assoc__:
                    -
                      - model
                      - 8xl
                    -
                      - title
                      - 8XL
                    -
                      - view
                      -
                        __assoc__:
                          -
                            - classes
                            -
                              - text-8xl
                          -
                            - name
                            - span
      -
        - link
        -
          __assoc__:
            -
              - addTargetToExternalLinks
              - false
            -
              - decorators
              -
                __assoc__:
                  -
                    - openInNewTab
                    -
                      __assoc__:
                        -
                          - attributes
                          -
                            __assoc__:
                              -
                                - rel
                                - 'noopener noreferrer'
                              -
                                - target
                                - _blank
                        -
                          - label
                          - 'Open in a new tab'
                        -
                          - mode
                          - manual
      -
        - style
        -
          __assoc__:
            -
              - definitions
              -
                -
                  __assoc__:
                    -
                      - classes
                      -
                        - bullet-list
                    -
                      - element
                      - ul
                    -
                      - name
                      - 'Bullet List'
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  toolbar:
    - bold
    - italic
    - link
    - '|'
    - bulletedList
    - numberedList
    - '|'
    - style
    - fontSize
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
