columnSuffix: null
handle: colorScheme
instructions: 'This field presets the colors of text, heading etc. in the section. Based on what background color you choose for the section (or in the case of a background photo, how dark the photo is) you select the color mode that will work best with the background. Colors can be overridden on the individual elements themselves if desired.'
name: 'Color Scheme'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Light Mode'
        -
          - template
          - ''
        -
          - background
          - ''
        -
          - value
          - color-theme-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Dark Mode'
        -
          - template
          - ''
        -
          - background
          - ''
        -
          - value
          - color-theme-dark
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: Imarc\Pickture\fields\PicktureField
