columnSuffix: null
handle: pageHeaderColorScheme
instructions: null
name: 'Page Header Color Scheme'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Light Mode'
        -
          - template
          - ''
        -
          - background
          - ''
        -
          - value
          - color-theme-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Dark Mode'
        -
          - template
          - ''
        -
          - background
          - ''
        -
          - value
          - color-theme-dark
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: Imarc\Pickture\fields\PicktureField
