columnSuffix: null
handle: subheadText
instructions: null
name: 'Subhead Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes:
    - b644bda8-1050-46f5-9453-0b3d19812289 # Documents
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: Simple.json
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - bold
    - italic
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
