defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 00b46567-7b31-49a0-a9ad-dbc2a79ea636 # Reusable Module
handle: reusableModules
maxAuthors: 1
minAuthors: 1
name: 'Reusable Modules'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  e6aadd12-c632-4735-b22d-b5a758ab5003: # Boilermaker 3
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
